version: 2.0

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy
          command: ls  # command: bash /tools/deploy.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:  master
