baseURL = "https://ergoplatform.org"
title = "Ergo"
languageCode = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
tags = ["development", "Go", "fast", "Blogging"]
pygmentsUseClasses=true

[taxonomies]
  tag = "tags"

# Links format
[permalinks]
  pages = "/:slug/"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  defaultLanguage = "en"
  description = "Ergo platform"

[languages.en]
  languageCode = "en"
  languageName = "Eng"
  contentDir = "content/en"
  weight = 1

  [[languages.en.menu.mainmenu]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = -110

  [[languages.en.menu.mainmenu]]
    identifier = "Foundation"
    name = "Foundation"
    url = "/foundation/"
    weight = -100

  [[languages.en.menu.mainmenu]]
    identifier = "news"
    name = "News"
    url = "/news/"
    weight = -90

  [[languages.en.menu.mainmenu]]
    identifier = "FAQ"
    name = "FAQ"
    url = "/faq/"
    weight = -80

  [[languages.en.menu.mainmenu]]
    identifier = "Documents"
    name = "Documents"
    url = "/documents/"
    weight = -70

  [[languages.en.menu.mainmenu]]
    identifier = "Tools"
    name = "Tools"
    url = "/tools/"
    weight = -60

  [[languages.en.menu.mainmenu]]
    identifier = "Blog"
    name = "Blog"
    url = "/blog/"
    weight = -50

  [[languages.en.menu.mainmenu]]
    identifier = "Team"
    name = "Team"
    url = "/team/"
    weight = -40

  # [[languages.en.menu.mainmenu]]
  #   identifier = "Careers"
  #   name = "Careers"
  #   url = "/careers/"
  #   weight = -40

[languages.cn]
  languageCode = "cn"
  languageName = "中文"
  contentDir = "content/cn"
  weight = 1

  [[languages.cn.menu.mainmenu]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = -110

  [[languages.cn.menu.mainmenu]]
    identifier = "Foundation"
    name = "Foundation"
    url = "/foundation/"
    weight = -100

  [[languages.cn.menu.mainmenu]]
    identifier = "news"
    name = "新闻"
    url = "/news/"
    weight = -90

  [[languages.cn.menu.mainmenu]]
    identifier = "FAQ"
    name = "常问问题"
    url = "/faq/"
    weight = -80

  [[languages.cn.menu.mainmenu]]
    identifier = "Documents"
    name = "文件"
    url = "/documents/"
    weight = -70

  [[languages.cn.menu.mainmenu]]
    identifier = "Tools"
    name = "工具"
    url = "/tools/"
    weight = -60

  [[languages.cn.menu.mainmenu]]
    identifier = "Blog"
    name = "博客"
    url = "/blog/"
    weight = -50

  [[languages.cn.menu.mainmenu]]
    identifier = "Team"
    name = "团队"
    url = "/team/"
    weight = -40
