baseURL = "https://ergoplatform.org"
languageCode = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
title = "Ergo"

# Links format
[permalinks]
  pages = "/:slug/"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  defaultLanguage = "en"
  description = "Ergo platform"

[languages.en]
  languageCode = "en"
  languageName = "English"
  contentDir = "content/en"
  weight = 1

  [[languages.en.menu.mainmenu]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = -110

  [[languages.en.menu.mainmenu]]
    identifier = "news"
    name = "News"
    url = "/news/"
    weight = -100

  [[languages.en.menu.mainmenu]]
    identifier = "FAQ"
    name = "FAQ"
    url = "/faq/"
    weight = -90

  [[languages.en.menu.mainmenu]]
    identifier = "Documents"
    name = "Documents"
    url = "/documents/"
    weight = -80

  [[languages.en.menu.mainmenu]]
    identifier = "Tools"
    name = "Tools"
    url = "/tools/"
    weight = -70

  [[languages.en.menu.mainmenu]]
    identifier = "Blog"
    name = "Blog"
    url = "/blog/"
    weight = -60

  [[languages.en.menu.mainmenu]]
    identifier = "Team"
    name = "Team"
    url = "/team/"
    weight = -50
