baseURL = "https://ergoplatform.org"
title = "Ergo"
subtitle = "Ergo page"
languageCode = "en"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
pygmentsUseClasses=true

# Links format
[permalinks]
  pages = "/:slug/"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  defaultLanguage = "en"
  description = "Ergo platform"

[languages.en]
  languageCode = "en"
  languageName = "Eng"
  contentDir = "content/en"
  weight = 1

  [[languages.en.menu.individuals]]
    identifier = "about"
    name = "Getting Started"
    url = "/about/"
    weight = 10
  [[languages.en.menu.individuals]]
    identifier = "basics"
    name = "Basics"
    url = "/basics/"
    weight = 20
  [[languages.en.menu.individuals]]
    identifier = "wallets"
    name = "Wallets"
    url = "/wallets/"
    weight = 30
  [[languages.en.menu.individuals]]
    identifier = "exchanges"
    name = "Exchanges"
    url = "/exchanges/"
    weight = 40

  [[languages.en.menu.developers]]
    identifier = "contribute"
    name = "Contribute to Ergo"
    url = "/contribute"
    weight = 10
  [[languages.en.menu.developers]]
    identifier = "software"
    name = "Software"
    url = "/software/"
    weight = 20
  [[languages.en.menu.developers]]
    identifier = "use_cases"
    name = "Use Cases"
    url = "/use_cases/"
    weight = 30
  [[languages.en.menu.developers]]
    identifier = "awesome"
    name = "Awesome Ergo"
    url = "https://github.com/ergoplatform/awesome-ergo"
    pre = 'true'
    weight = 50

  [[languages.en.menu.community]]
    identifier = "foundation"
    name = "Foundation"
    url = "/foundation"
    weight = 10
  [[languages.en.menu.community]]
    identifier = "Hall of Fame"
    name = "Hall of Fame"
    url = "/hall_of_fame/"
    weight = 20
  [[languages.en.menu.community]]
    identifier = "news"
    name = "News"
    url = "/news/"
    weight = 30
  [[languages.en.menu.community]]
    identifier = "Blog"
    name = "Blog"
    url = "/blog/"
    weight = 40
  [[languages.en.menu.community]]
    identifier = "forum"
    name = "Forum"
    url = "https://www.ergoforum.org/"
    pre = 'true'
    weight = 50
  [[languages.en.menu.community]]
    identifier = "wiki"
    name = "Wiki"
    url = "https://ergonaut.space/"
    weight = 60
    pre = 'true'

  [[languages.en.menu.other]]
    identifier = "Documents"
    name = "Documents"
    url = "/documents/"
    weight = 10

  [[languages.en.menu.other]]
    identifier = "FAQ"
    name = "FAQ"
    url = "/faq/"
    weight = 20

  [[languages.en.menu.other]]
    identifier = "Mining"
    name = "Mining"
    url = "/mining/"
    weight = 30

  [[languages.en.menu.other]]
    identifier = "Explorer"
    name = "Explorer"
    url = "https://explorer.ergoplatform.com/"
    pre = 'true'
    weight = 40

  [[languages.en.menu.other]]
    identifier = "dApps"
    name = "DApps"
    weight = 50
    url = "https://sigmaverse.io/"
    pre = 'true'

[languages.cn]
  languageCode = "cn"
  languageName = "中文"
  contentDir = "content/cn"
  weight = 2

  [[languages.cn.menu.individuals]]
    identifier = "about"
    name = "Getting Started"
    url = "/about/"
    weight = 10
  [[languages.cn.menu.individuals]]
    identifier = "basics"
    name = "Basics"
    url = "/basics/"
    weight = 20
  [[languages.cn.menu.individuals]]
    identifier = "wallets"
    name = "Wallets"
    url = "/wallets/"
    weight = 30
  [[languages.cn.menu.individuals]]
    identifier = "exchanges"
    name = "Exchanges"
    url = "/exchanges/"
    weight = 40

  [[languages.cn.menu.developers]]
    identifier = "contribute"
    name = "Contribute to Ergo"
    url = "/contribute"
    weight = 10
  [[languages.cn.menu.developers]]
    identifier = "software"
    name = "Software"
    url = "/software/"
    weight = 20
  [[languages.cn.menu.developers]]
    identifier = "use_cases"
    name = "Use Cases"
    url = "/use_cases/"
    weight = 30
  [[languages.cn.menu.developers]]
    identifier = "awesome"
    name = "Awesome Ergo"
    url = "https://github.com/ergoplatform/awesome-ergo"
    pre = 'true'
    weight = 50

  [[languages.cn.menu.community]]
    identifier = "foundation"
    name = "Foundation"
    url = "/foundation"
    weight = 10
  [[languages.cn.menu.community]]
    identifier = "Hall of Fame"
    name = "Hall of Fame"
    url = "/hall_of_fame/"
    weight = 20
  [[languages.cn.menu.community]]
    identifier = "news"
    name = "News"
    url = "/news/"
    weight = 30
  [[languages.cn.menu.community]]
    identifier = "Blog"
    name = "Blog"
    url = "/blog/"
    weight = 40
  [[languages.cn.menu.community]]
    identifier = "forum"
    name = "Forum"
    url = "https://www.ergoforum.org/"
    pre = 'true'
    weight = 50
  [[languages.cn.menu.community]]
    identifier = "wiki"
    name = "Wiki"
    url = "https://ergonaut.space/"
    weight = 60
    pre = 'true'

  [[languages.cn.menu.other]]
    identifier = "Documents"
    name = "Documents"
    url = "/documents/"
    weight = 10

  [[languages.cn.menu.other]]
    identifier = "FAQ"
    name = "FAQ"
    url = "/faq/"
    weight = 20

  [[languages.cn.menu.other]]
    identifier = "Mining"
    name = "Mining"
    url = "/mining/"
    weight = 30

  [[languages.cn.menu.other]]
    identifier = "Explorer"
    name = "Explorer"
    url = "https://explorer.ergoplatform.com/"
    pre = 'true'
    weight = 40

  [[languages.cn.menu.other]]
    identifier = "dApps"
    name = "DApps"
    weight = 50
    url = "https://sigmaverse.io/"
    pre = 'true'

[languages.pl]
  languageCode = "pl"
  languageName = "Pol"
  contentDir = "content/pl"
  weight = 3

  [[languages.pl.menu.individuals]]
    identifier = "about"
    name = "Getting Started"
    url = "/about/"
    weight = 10
  [[languages.pl.menu.individuals]]
    identifier = "basics"
    name = "Basics"
    url = "/basics/"
    weight = 20
  [[languages.pl.menu.individuals]]
    identifier = "wallets"
    name = "Wallets"
    url = "/wallets/"
    weight = 30
  [[languages.pl.menu.individuals]]
    identifier = "exchanges"
    name = "Exchanges"
    url = "/exchanges/"
    weight = 40

  [[languages.pl.menu.developers]]
    identifier = "contribute"
    name = "Contribute to Ergo"
    url = "/contribute"
    weight = 10
  [[languages.pl.menu.developers]]
    identifier = "software"
    name = "Software"
    url = "/software/"
    weight = 20
  [[languages.pl.menu.developers]]
    identifier = "use_cases"
    name = "Use Cases"
    url = "/use_cases/"
    weight = 30
  [[languages.pl.menu.developers]]
    identifier = "awesome"
    name = "Awesome Ergo"
    url = "https://github.com/ergoplatform/awesome-ergo"
    pre = 'true'
    weight = 40

  [[languages.pl.menu.community]]
    identifier = "foundation"
    name = "Foundation"
    url = "/foundation"
    weight = 10

  [[languages.pl.menu.community]]
    identifier = "Hall of Fame"
    name = "Hall of Fame"
    url = "/hall_of_fame/"
    weight = 20

  [[languages.pl.menu.community]]
    identifier = "news"
    name = "News"
    url = "/news/"
    weight = 30
  [[languages.pl.menu.community]]
    identifier = "Blog"
    name = "Blog"
    url = "/blog/"
    weight = 40
  [[languages.pl.menu.community]]
    identifier = "forum"
    name = "Forum"
    url = "https://www.ergoforum.org/"
    pre = 'true'
    weight = 50
  [[languages.pl.menu.community]]
    identifier = "wiki"
    name = "Wiki"
    url = "https://ergonaut.space/"
    weight = 60
    pre = 'true'

  [[languages.pl.menu.other]]
    identifier = "Documents"
    name = "Documents"
    url = "/documents/"
    weight = 10

  [[languages.pl.menu.other]]
    identifier = "FAQ"
    name = "FAQ"
    url = "/faq/"
    weight = 20

  [[languages.pl.menu.other]]
    identifier = "Mining"
    name = "Mining"
    url = "/mining/"
    weight = 30

  [[languages.pl.menu.other]]
    identifier = "Explorer"
    name = "Explorer"
    url = "https://explorer.ergoplatform.com/"
    pre = 'true'
    weight = 40

  [[languages.pl.menu.other]]
    identifier = "dApps"
    name = "DApps"
    weight = 50
    url = "https://sigmaverse.io/"
    pre = 'true'

[languages.de]
  languageCode = "de"
  languageName = "Deu"
  contentDir = "content/de"
  weight = 1

  [[languages.de.menu.individuals]]
    identifier = "about"
    name = "Erste Schritte"
    url = "/about/"
    weight = 10
  [[languages.de.menu.individuals]]
    identifier = "basics"
    name = "Basics"
    url = "/basics/"
    weight = 20
  [[languages.de.menu.individuals]]
    identifier = "wallets"
    name = "Wallets"
    url = "/wallets/"
    weight = 30
  [[languages.de.menu.individuals]]
    identifier = "exchanges"
    name = "Exchanges"
    url = "/exchanges/"
    weight = 40

  [[languages.de.menu.developers]]
    identifier = "contribute"
    name = "Mach mit bei Ergo"
    url = "/contribute"
    weight = 10
  [[languages.de.menu.developers]]
    identifier = "software"
    name = "Software"
    url = "/software/"
    weight = 20
  [[languages.de.menu.developers]]
    identifier = "use_cases"
    name = "Use Cases"
    url = "/use_cases/"
    weight = 30
  [[languages.de.menu.developers]]
    identifier = "awesome"
    name = "Awesome Ergo"
    url = "https://github.com/ergoplatform/awesome-ergo"
    pre = 'true'
    weight = 40

  [[languages.de.menu.community]]
    identifier = "foundation"
    name = "Foundation"
    url = "/foundation"
    weight = 10
  [[languages.de.menu.community]]
    identifier = "Hall of Fame"
    name = "Hall of Fame"
    url = "/hall_of_fame/"
    weight = 20
  [[languages.de.menu.community]]
    identifier = "news"
    name = "News"
    url = "/news/"
    weight = 30
  [[languages.de.menu.community]]
    identifier = "Blog"
    name = "Blog"
    url = "/blog/"
    weight = 40
  [[languages.de.menu.community]]
    identifier = "forum"
    name = "Forum"
    url = "https://www.ergoforum.org/"
    pre = 'true'
    weight = 50
  [[languages.de.menu.community]]
    identifier = "wiki"
    name = "Wiki"
    url = "https://ergonaut.space/"
    weight = 60
    pre = 'true'

  [[languages.de.menu.other]]
    identifier = "Documents"
    name = "Dokumente"
    url = "/documents/"
    weight = 10

  [[languages.de.menu.other]]
    identifier = "FAQ"
    name = "FAQ"
    url = "/faq/"
    weight = 20

  [[languages.de.menu.other]]
    identifier = "Mining"
    name = "Minen"
    url = "/mining/"
    weight = 30

  [[languages.de.menu.other]]
    identifier = "Explorer"
    name = "Explorer"
    url = "https://explorer.ergoplatform.com/"
    pre = 'true'
    weight = 40

  [[languages.de.menu.other]]
    identifier = "dApps"
    name = "DApps"
    weight = 50
    url = "https://sigmaverse.io/"
    pre = 'true'

[languages.sk]
  languageCode = "sk"
  languageName = "Sk"
  contentDir = "content/sk"
  weight = 4

  [[languages.sk.menu.individuals]]
    identifier = "about"
    name = "Getting Started"
    url = "/about/"
    weight = 10
  [[languages.sk.menu.individuals]]
    identifier = "basics"
    name = "Basics"
    url = "/basics/"
    weight = 20
  [[languages.sk.menu.individuals]]
    identifier = "wallets"
    name = "Wallets"
    url = "/wallets/"
    weight = 30
  [[languages.sk.menu.individuals]]
    identifier = "exchanges"
    name = "Exchanges"
    url = "/exchanges/"
    weight = 40

  [[languages.sk.menu.developers]]
    identifier = "contribute"
    name = "Contribute to Ergo"
    url = "/contribute"
    weight = 10
  [[languages.sk.menu.developers]]
    identifier = "software"
    name = "Software"
    url = "/software/"
    weight = 20
  [[languages.sk.menu.developers]]
    identifier = "use_cases"
    name = "Use Cases"
    url = "/use_cases/"
    weight = 30
  [[languages.sk.menu.developers]]
    identifier = "awesome"
    name = "Awesome Ergo"
    url = "https://github.com/ergoplatform/awesome-ergo"
    pre = 'true'
    weight = 40

  [[languages.sk.menu.community]]
    identifier = "foundation"
    name = "Foundation"
    url = "/foundation"
    weight = 10
  [[languages.sk.menu.community]]
    identifier = "Hall of Fame"
    name = "Hall of Fame"
    url = "/hall_of_fame/"
    weight = 20
  [[languages.sk.menu.community]]
    identifier = "news"
    name = "News"
    url = "/news/"
    weight = 30
  [[languages.sk.menu.community]]
    identifier = "Blog"
    name = "Blog"
    url = "/blog/"
    weight = 40
  [[languages.sk.menu.community]]
    identifier = "forum"
    name = "Forum"
    url = "https://www.ergoforum.org/"
    pre = 'true'
    weight = 50
  [[languages.sk.menu.community]]
    identifier = "wiki"
    name = "Wiki"
    url = "https://ergonaut.space/"
    weight = 60
    pre = 'true'

  [[languages.sk.menu.other]]
    identifier = "Documents"
    name = "Documents"
    url = "/documents/"
    weight = 10

  [[languages.sk.menu.other]]
    identifier = "FAQ"
    name = "FAQ"
    url = "/faq/"
    weight = 20

  [[languages.sk.menu.other]]
    identifier = "Mining"
    name = "Mining"
    url = "/mining/"
    weight = 30

  [[languages.sk.menu.other]]
    identifier = "Explorer"
    name = "Explorer"
    url = "https://explorer.ergoplatform.com/"
    pre = 'true'
    weight = 40

  [[languages.sk.menu.other]]
    identifier = "dApps"
    name = "DApps"
    weight = 50
    url = "https://sigmaverse.io/"
    pre = 'true'

[outputFormats]
  [html]
    minify = true
  [json]
    minify = true
